WebApplication1/WebApplication1/Controllers/ArchivoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Configuration;
using System.Data.OleDb;
using System.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ArchivoController : Controller
    {
        // GET: Archivo
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase postedFile)
        {
            string filePath = string.Empty;
            DataSet ExcelData = new DataSet();
            DataTable dtSheet = new DataTable();
            if (postedFile != null)
            {
                string path = Server.MapPath("~/Uploads/");
                if (Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                filePath = path + Path.GetFileName(postedFile.FileName);
                string extension = Path.GetExtension(postedFile.FileName);
                postedFile.SaveAs(filePath);

                string conString = string.Empty;
                if (extension == ".xls")
                {
                    conString = ConfigurationManager.ConnectionStrings["Excel03ConString"].ConnectionString;
                }
                else if (extension == ".xlsx")
                {
                    conString = ConfigurationManager.ConnectionStrings["Excel07ConString"].ConnectionString;
                }
                else
                {
                    ViewBag.Error = "El archivo a mostrar debe ser tipo (xls, xlsx).";
                    return View();
                }

                conString = string.Format(conString, filePath);
                using (OleDbConnection connExcel = new OleDbConnection(conString))
                {
                    using (OleDbCommand cmdExcel = new OleDbCommand())
                    {
                        using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())
                        {

                            cmdExcel.Connection = connExcel;
                            connExcel.Open();
                            DataTable dtExcelSchema;
                            dtExcelSchema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                            string sheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();
                            connExcel.Close();

                            connExcel.Open();
                            cmdExcel.CommandText = "SELECT * From [" + sheetName + "]";
                            odaExcel.SelectCommand = cmdExcel;
                            odaExcel.Fill(dtSheet);
                            connExcel.Close();
                        }
                    }
                }
            }
            ExcelData.Tables.Add(dtSheet);
            return View(ExcelData);
        }
    }
}

WebApplication1/WebApplication1/Views/Archivo/Index.cshtml
@using System.Data;
@model DataSet
@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="~/Content/Style1.css" />
    <meta name="viewport" content="width=device-width" />
    <title>Archivos</title>
</head>
<body>
    <br />
    <h2 align="center">Cargar y mostrar un archivo Excel</h2>
    @using (Html.BeginForm("Index", "Archivo", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.ViewBag.Error<br />
        <input type="file" name="postedFile" class="btn-default" />
        <input type="submit" value="Import" class="btn boton btn-primary" />
    }
    <div id="formulario">
        @if (Model != null)
        {
            <table cellpadding="0" cellspacing="0" align="center">
                <tr>
                    @foreach (DataColumn col in Model.Tables[0].Columns)
                    {
                        <th>@col.ColumnName</th>
                    }
                </tr>
                @foreach (DataRow row in Model.Tables[0].Rows)
                {
                    <tr>
                        @foreach (DataColumn col in Model.Tables[0].Columns)
                        {
                            <td>@row[col.ColumnName]</td>
                        }
                    </tr>
                }
            </table>
        }
    </div>
</body>
</html>